export interface IVehicleDef {
    // year: number | [number, number];
    // make: string;
    // model: string;
    // engine: string;

    _id: string;
    site: number;
    status: string;
    itemId: string;
    price: number;
    make: string;
    makeEn: string;
    picture: string[];
    mileage: number;
    model: string;
    planA: number;
    planB: number | null;
    repairHistory: string;
    specification: any[];
    title: string;
    offerPrice: string;
    salePrice: number;
    url: string;
    inspectionMonth?: number;
    inspectionYear?: number;
    modelYear: number;// | [number, number];
    pageNo: number;
    mfgData: string;
    mfgYear: number;
    regYear: number;
    regMonth?: number;
    chassisNo: string;
    width: string;
    height: string;
    length: string;
    m3: string;
    doors: string;
    seatCapacity: number;
    location: string;
    fuel: string;
    color: string;
    wheelDrive: string;
    bodyType: string;
    engineType: string;
    transmission: string;
    wheelbase: string;
    vehicleWeight: string;
    indoor: string;
    JC08FuelEconomy: string;
    WLTCFuelEconomy: string;
    minimumTurningRadius: string;
    numberOfSheetRows: string;
    steering: string;
    condition: string;
    updatedAt: string;
    createdAt: string;
    __v: number;
    id: string;
}
